{
    "openapi": "3.0.0",
    "info": {
        "title": "Geocoders API",
        "version": "1.0.0",
        "description": "API that powers geospatial applications"
    },
    "servers": [
        {
            "url": "https://api.geocoders.io"
        },
        {
            "url": "https://api-test.geocoders.io"
        }
    ],
    "security": [
        {
            "ApiKeyAuth": []
        }
    ],
    "paths": {
        "/geocode/forward": {
            "post": {
                "tags": [
                    "geocoding"
                ],
                "description": "Convert an address to latitude/longitude pair",
                "summary": "/geocode/forward",
                "requestBody": {
                    "description": "Adress to forward geocode",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/GeocodeForwardInput",
                                "example": {
                                    "streetname": "West-Kruiskade",
                                    "number": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Forward geocode response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GeocodeForwardResponse",
                                    "example": {
                                        "suburb_id": "d24c1500-3e37-461e-98f6-ef54713928e4",
                                        "building_id": "2bc27c19-bc93-4526-b096-c2a8203c1386",
                                        "number": "1",
                                        "suffix": "A",
                                        "streetname": "West-Kruiskade",
                                        "postcode": "3014AJ",
                                        "city": "3014AJ",
                                        "longitude": 4.470474881149264,
                                        "latitude": 51.92091314785285
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/geocode/reverse": {
            "post": {
                "tags": [
                    "geocoding"
                ],
                "description": "Convert a latitude/longitude pair to address",
                "summary": "/geocode/reverse",
                "requestBody": {
                    "description": "Latitude/longitude pair to reverse Geocode",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/GeocodeReverseInput",
                                "example": {
                                    "latitude": 51.92091314785285,
                                    "longitude": 4.470474881149264
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Reverse geocode response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GeocodeReverseResponse",
                                    "example": {
                                        "suburb_id": "d24c1500-3e37-461e-98f6-ef54713928e4",
                                        "building_id": "2bc27c19-bc93-4526-b096-c2a8203c1386",
                                        "number": "1",
                                        "suffix": "A",
                                        "streetname": "West-Kruiskade",
                                        "postcode": "3014AJ",
                                        "city": "Rotterdam"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/lookup/postcode": {
            "post": {
                "tags": [
                    "postcode"
                ],
                "description": "Address lookup for given postcode",
                "summary": "/lookup/postcode",
                "requestBody": {
                    "description": "Postcode to convert to address",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/LookupPostcodeInput",
                                "example": {
                                    "postcode": "3014AJ",
                                    "number": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Lookup Postcode response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/LookupPostcodeResponse",
                                    "example": {
                                        "suburb_id": "d24c1500-3e37-461e-98f6-ef54713928e4",
                                        "building_id": "2bc27c19-bc93-4526-b096-c2a8203c1386",
                                        "number": "1",
                                        "suffix": "A",
                                        "streetname": "West-Kruiskade",
                                        "postcode": "3014AJ",
                                        "city": "Rotterdam",
                                        "longitude": 4.470474881149264,
                                        "latitude": 51.92091314785285
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/countries": {
            "get": {
                "tags": [
                    "countries"
                ],
                "description": "List Countries",
                "summary": "/countries",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "name to filter by",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "country_code",
                        "in": "query",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List Countries response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Country"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/countries/{id}": {
            "get": {
                "tags": [
                    "countries"
                ],
                "description": "Get Country",
                "summary": "/countries/:id",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of Country to get",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Country response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Country"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-Api-Key"
            }
        },
        "schemas": {
            "GeocodeForwardInput": {
                "type": "object",
                "required": [
                    "streetname",
                    "number"
                ],
                "properties": {
                    "streetname": {
                        "type": "string"
                    },
                    "number": {
                        "type": "string"
                    },
                    "suffix": {
                        "type": "string"
                    },
                    "suburb": {
                        "type": "string"
                    },
                    "province": {
                        "type": "string"
                    }
                }
            },
            "GeocodeForwardResponse": {
                "type": "object",
                "properties": {
                    "suburb_id": {
                        "type": "string"
                    },
                    "building_id": {
                        "type": "string",
                        "nullable": true
                    },
                    "number": {
                        "type": "string",
                        "nullable": true
                    },
                    "suffix": {
                        "type": "string",
                        "nullable": true
                    },
                    "streetname": {
                        "type": "string",
                        "nullable": true
                    },
                    "postcode": {
                        "type": "string",
                        "nullable": true
                    },
                    "city": {
                        "type": "string",
                        "nullable": true
                    },
                    "latitude": {
                        "type": "number",
                        "format": "float"
                    },
                    "longitude": {
                        "type": "number",
                        "format": "float"
                    }
                }
            },
            "GeocodeReverseInput": {
                "type": "object",
                "required": [
                    "latitude",
                    "longitude"
                ],
                "properties": {
                    "latitude": {
                        "type": "number",
                        "format": "float"
                    },
                    "longitude": {
                        "type": "number",
                        "format": "float"
                    }
                }
            },
            "GeocodeReverseResponse": {
                "type": "object",
                "properties": {
                    "suburb_id": {
                        "type": "string"
                    },
                    "building_id": {
                        "type": "string",
                        "nullable": true
                    },
                    "number": {
                        "type": "string",
                        "nullable": true
                    },
                    "suffix": {
                        "type": "string",
                        "nullable": true
                    },
                    "streetname": {
                        "type": "string",
                        "nullable": true
                    },
                    "postcode": {
                        "type": "string",
                        "nullable": true
                    },
                    "city": {
                        "type": "string",
                        "nullable": true
                    }
                }
            },
            "LookupPostcodeInput": {
                "type": "object",
                "required": [
                    "postcode",
                    "number"
                ],
                "properties": {
                    "postcode": {
                        "type": "string"
                    },
                    "number": {
                        "type": "string"
                    }
                }
            },
            "LookupPostcodeResponse": {
                "type": "object",
                "properties": {
                    "suburb_id": {
                        "type": "string"
                    },
                    "building_id": {
                        "type": "string",
                        "nullable": true
                    },
                    "number": {
                        "type": "string",
                        "nullable": true
                    },
                    "suffix": {
                        "type": "string",
                        "nullable": true
                    },
                    "streetname": {
                        "type": "string"
                    },
                    "postcode": {
                        "type": "string",
                        "nullable": true
                    },
                    "city": {
                        "type": "string",
                        "nullable": true
                    },
                    "latitude": {
                        "type": "number",
                        "format": "float"
                    },
                    "longitude": {
                        "type": "number",
                        "format": "float"
                    }
                }
            },
            "Country": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "country_code": {
                        "type": "string"
                    },
                    "alt_name": {
                        "type": "string"
                    },
                    "local_identifier": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
